version: '3.7'

services:
  dinder-frontend:
    build: ./dinder-frontend
    volumes:
      - './dinder-frontend:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on: 
        - dinder
    
  dinder:
    build: ./dinder
    volumes:
      - ./dinder:/go/src/dinder
    depends_on:
      - redis
    ports:
      - 8080:8081
    links:
      - redis
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  # Redis Service
  redis:
    image: 'redis:alpine' # Use a public Redis image to build the redis service
    restart: unless-stopped
    networks:
      - backend


networks:
  backend:
